from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .integration_models import MqttAddonGrant, MqttIntegrationState, MqttPrincipal
from .topic_families import BOOTSTRAP_TOPIC


DEFAULT_RESERVED_PREFIXES: tuple[str, ...] = (
    "synthia/system/#",
    "synthia/core/#",
    "synthia/supervisor/#",
    "synthia/scheduler/#",
    "synthia/policy/#",
    "synthia/telemetry/#",
)
DEFAULT_BOOTSTRAP_TOPIC = BOOTSTRAP_TOPIC


@dataclass(frozen=True)
class CompiledAclRule:
    principal_id: str
    action: str
    topic: str
    effect: str


@dataclass(frozen=True)
class MqttAclCompilationResult:
    rules: list[CompiledAclRule]
    acl_text: str


def _sorted_unique(items: Iterable[str]) -> list[str]:
    return sorted({str(item).strip() for item in items if str(item).strip()})


class MqttAclCompiler:
    def __init__(
        self,
        *,
        bootstrap_topic: str = DEFAULT_BOOTSTRAP_TOPIC,
        reserved_prefixes: Iterable[str] | None = None,
    ) -> None:
        self._bootstrap_topic = str(bootstrap_topic or DEFAULT_BOOTSTRAP_TOPIC).strip() or DEFAULT_BOOTSTRAP_TOPIC
        self._reserved = _sorted_unique(reserved_prefixes or DEFAULT_RESERVED_PREFIXES)

    def compile(self, state: MqttIntegrationState) -> MqttAclCompilationResult:
        rules: list[CompiledAclRule] = []

        rules.append(CompiledAclRule("anonymous", "subscribe", self._bootstrap_topic, "allow"))
        rules.append(CompiledAclRule("anonymous", "publish", "#", "deny"))
        rules.append(CompiledAclRule("anonymous", "subscribe", "#", "deny"))
        for prefix in self._reserved:
            rules.append(CompiledAclRule("generic_user:*", "publish", prefix, "deny"))
            rules.append(CompiledAclRule("generic_user:*", "subscribe", prefix, "deny"))

        for principal in sorted(state.principals.values(), key=lambda item: item.principal_id):
            rules.extend(self._rules_for_principal(principal, state))

        normalized = sorted(set(rules), key=lambda item: (item.principal_id, item.action, item.topic, item.effect))
        return MqttAclCompilationResult(rules=normalized, acl_text=self._to_acl_text(normalized))

    def _rules_for_principal(self, principal: MqttPrincipal, state: MqttIntegrationState) -> list[CompiledAclRule]:
        if principal.status in {"revoked", "expired"}:
            return []
        if principal.principal_type == "generic_user":
            return []
        if principal.principal_type not in {"synthia_addon", "synthia_node"}:
            return []

        grant = self._grant_for_principal(principal, state)
        if grant is None:
            return []
        out: list[CompiledAclRule] = []
        for topic in _sorted_unique(grant.publish_topics):
            out.append(CompiledAclRule(principal.principal_id, "publish", topic, "allow"))
        for topic in _sorted_unique(grant.subscribe_topics):
            out.append(CompiledAclRule(principal.principal_id, "subscribe", topic, "allow"))
        return out

    def _grant_for_principal(self, principal: MqttPrincipal, state: MqttIntegrationState) -> MqttAddonGrant | None:
        if principal.linked_addon_id:
            grant = state.active_grants.get(principal.linked_addon_id)
            if grant is None:
                return None
            if grant.status not in {"approved", "active", "provisioned"}:
                return None
            return grant
        return None

    def _to_acl_text(self, rules: list[CompiledAclRule]) -> str:
        lines: list[str] = []
        lines.append("# generated by synthia core mqtt acl compiler")
        for rule in rules:
            lines.append(f"{rule.principal_id} {rule.effect} {rule.action} {rule.topic}")
        return "\n".join(lines) + "\n"
