from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MqttListenerSpec:
    name: str
    enabled: bool
    port: int
    bind_address: str = "0.0.0.0"
    allow_anonymous: bool = False


@dataclass(frozen=True)
class MqttBrokerRenderInput:
    provider: str
    acl_file: str
    password_file: str
    data_dir: str
    log_dir: str
    listeners: list[MqttListenerSpec]


@dataclass(frozen=True)
class MqttBrokerRenderOutput:
    files: dict[str, str]


class MqttBrokerConfigRenderer:
    def render(self, item: MqttBrokerRenderInput) -> MqttBrokerRenderOutput:
        listeners = [listener for listener in sorted(item.listeners, key=lambda x: x.name) if listener.enabled]
        files: dict[str, str] = {
            "acl.conf": self._render_acl_ref(item.acl_file),
            "auth.conf": self._render_auth_ref(item.password_file),
            "listeners.conf": self._render_listeners(listeners),
            "broker.conf": self._render_main(item, listeners),
        }
        broker_conf = str(files.get("broker.conf") or "")
        if not broker_conf.strip():
            raise ValueError("broker_conf_empty")
        return MqttBrokerRenderOutput(files=files)

    def _render_main(self, item: MqttBrokerRenderInput, listeners: list[MqttListenerSpec]) -> str:
        lines = [
            "# generated by synthia core mqtt config renderer",
            f"# provider={item.provider}",
            "per_listener_settings true",
            "persistence true",
            f"persistence_location {item.data_dir}",
            f"log_dest file {item.log_dir.rstrip('/')}/broker.log",
        ]
        for listener in listeners:
            lines.append(f"# listener: {listener.name}")
            lines.append(f"listener {int(listener.port)} {listener.bind_address}")
            lines.append(f"listener_allow_anonymous {'true' if listener.allow_anonymous else 'false'}")
            lines.append(f"password_file {item.password_file}")
            lines.append(f"acl_file {item.acl_file}")
        return "\n".join(lines) + "\n"

    def _render_listeners(self, listeners: list[MqttListenerSpec]) -> str:
        lines = ["# generated listener config"]
        for listener in listeners:
            lines.append(f"# listener: {listener.name}")
            lines.append(f"listener {int(listener.port)} {listener.bind_address}")
            lines.append(f"allow_anonymous {'true' if listener.allow_anonymous else 'false'}")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _render_auth_ref(password_file: str) -> str:
        return "\n".join(
            [
                "# generated auth config",
                f"password_file {password_file}",
            ]
        ) + "\n"

    @staticmethod
    def _render_acl_ref(acl_file: str) -> str:
        return "\n".join(
            [
                "# generated acl config",
                f"acl_file {acl_file}",
            ]
        ) + "\n"
